# Generated by Django 3.2.8 on 2022-12-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_auto_20221208_1621'),
        ('store', '0046_auto_20221212_1710'),
    ]

    operations = [
    ]
